/*
 * fiber_port_select.h
 *
 * Deterministic Cortex-M port selection and architecture feature gates.
 */

#ifndef FIBER_PORT_FIBER_PORT_SELECT_H_
#define FIBER_PORT_FIBER_PORT_SELECT_H_

/*
 * FreeRTOS-style explicit profile selection. AUTO keeps the small-library
 * convenience path and derives the profile from compiler-provided
 * __ARM_ARCH_* macros. Production integrations may define FIBER_PORT_PROFILE
 * to one of the named values below.
 */
#define FIBER_PORT_PROFILE_AUTO             0
#define FIBER_PORT_PROFILE_ARMV6M           1
#define FIBER_PORT_PROFILE_ARMV7M           2
#define FIBER_PORT_PROFILE_ARMV7EM          3
#define FIBER_PORT_PROFILE_ARMV8M_BASELINE  4
#define FIBER_PORT_PROFILE_ARMV8M_MAINLINE  5
#define FIBER_PORT_PROFILE_ARMV81M_MAINLINE 6

#ifndef FIBER_PORT_PROFILE
# define FIBER_PORT_PROFILE FIBER_PORT_PROFILE_AUTO
#endif

BT_STATIC_ASSERT((FIBER_PORT_PROFILE == FIBER_PORT_PROFILE_AUTO) ||
                 (FIBER_PORT_PROFILE == FIBER_PORT_PROFILE_ARMV6M) ||
                 (FIBER_PORT_PROFILE == FIBER_PORT_PROFILE_ARMV7M) ||
                 (FIBER_PORT_PROFILE == FIBER_PORT_PROFILE_ARMV7EM) ||
                 (FIBER_PORT_PROFILE == FIBER_PORT_PROFILE_ARMV8M_BASELINE) ||
                 (FIBER_PORT_PROFILE == FIBER_PORT_PROFILE_ARMV8M_MAINLINE) ||
                 (FIBER_PORT_PROFILE == FIBER_PORT_PROFILE_ARMV81M_MAINLINE),
                 "[fiber]: unsupported FIBER_PORT_PROFILE");

#define FIBER_PORT_PROFILE_IS_EXPLICIT \
    (FIBER_PORT_PROFILE != FIBER_PORT_PROFILE_AUTO)

BT_STATIC_ASSERT((FIBER_PORT_PROFILE_IS_EXPLICIT == 0) || (FIBER_PORT_PROFILE_IS_EXPLICIT == 1),
                 "[fiber]: FIBER_PORT_PROFILE_IS_EXPLICIT must be 0 or 1");

#ifndef FIBER_PORT_DETECTED_ARMV6M
# if defined(__ARM_ARCH_6M__)
#  define FIBER_PORT_DETECTED_ARMV6M 1
# else
#  define FIBER_PORT_DETECTED_ARMV6M 0
# endif
#endif

#ifndef FIBER_PORT_DETECTED_ARMV7M
# if defined(__ARM_ARCH_7M__)
#  define FIBER_PORT_DETECTED_ARMV7M 1
# else
#  define FIBER_PORT_DETECTED_ARMV7M 0
# endif
#endif

#ifndef FIBER_PORT_DETECTED_ARMV7EM
# if defined(__ARM_ARCH_7EM__)
#  define FIBER_PORT_DETECTED_ARMV7EM 1
# else
#  define FIBER_PORT_DETECTED_ARMV7EM 0
# endif
#endif

#ifndef FIBER_PORT_DETECTED_ARMV8M_BASELINE
# if defined(__ARM_ARCH_8M_BASE__)
#  define FIBER_PORT_DETECTED_ARMV8M_BASELINE 1
# else
#  define FIBER_PORT_DETECTED_ARMV8M_BASELINE 0
# endif
#endif

#ifndef FIBER_PORT_DETECTED_ARMV8M_MAINLINE
/* ARMv8.1-M is a mainline superset. If MVE is enabled, detect v8.1-M. */
# if defined(__ARM_ARCH_8M_MAIN__) && \
     !defined(__ARM_ARCH_8_1M_MAIN__) && \
     !(defined(__ARM_FEATURE_MVE) && (__ARM_FEATURE_MVE > 0))
#  define FIBER_PORT_DETECTED_ARMV8M_MAINLINE 1
# else
#  define FIBER_PORT_DETECTED_ARMV8M_MAINLINE 0
# endif
#endif

#ifndef FIBER_PORT_DETECTED_ARMV81M_MAINLINE
# if defined(__ARM_ARCH_8_1M_MAIN__) || \
     (defined(__ARM_FEATURE_MVE) && (__ARM_FEATURE_MVE > 0))
#  define FIBER_PORT_DETECTED_ARMV81M_MAINLINE 1
# else
#  define FIBER_PORT_DETECTED_ARMV81M_MAINLINE 0
# endif
#endif

BT_STATIC_ASSERT((FIBER_PORT_DETECTED_ARMV6M == 0) || (FIBER_PORT_DETECTED_ARMV6M == 1),
                 "[fiber]: FIBER_PORT_DETECTED_ARMV6M must be 0 or 1");
BT_STATIC_ASSERT((FIBER_PORT_DETECTED_ARMV7M == 0) || (FIBER_PORT_DETECTED_ARMV7M == 1),
                 "[fiber]: FIBER_PORT_DETECTED_ARMV7M must be 0 or 1");
BT_STATIC_ASSERT((FIBER_PORT_DETECTED_ARMV7EM == 0) || (FIBER_PORT_DETECTED_ARMV7EM == 1),
                 "[fiber]: FIBER_PORT_DETECTED_ARMV7EM must be 0 or 1");
BT_STATIC_ASSERT((FIBER_PORT_DETECTED_ARMV8M_BASELINE == 0) || (FIBER_PORT_DETECTED_ARMV8M_BASELINE == 1),
                 "[fiber]: FIBER_PORT_DETECTED_ARMV8M_BASELINE must be 0 or 1");
BT_STATIC_ASSERT((FIBER_PORT_DETECTED_ARMV8M_MAINLINE == 0) || (FIBER_PORT_DETECTED_ARMV8M_MAINLINE == 1),
                 "[fiber]: FIBER_PORT_DETECTED_ARMV8M_MAINLINE must be 0 or 1");
BT_STATIC_ASSERT((FIBER_PORT_DETECTED_ARMV81M_MAINLINE == 0) || (FIBER_PORT_DETECTED_ARMV81M_MAINLINE == 1),
                 "[fiber]: FIBER_PORT_DETECTED_ARMV81M_MAINLINE must be 0 or 1");

#define FIBER_PORT_DETECTED_COUNT \
    (FIBER_PORT_DETECTED_ARMV6M + \
     FIBER_PORT_DETECTED_ARMV7M + \
     FIBER_PORT_DETECTED_ARMV7EM + \
     FIBER_PORT_DETECTED_ARMV8M_BASELINE + \
     FIBER_PORT_DETECTED_ARMV8M_MAINLINE + \
     FIBER_PORT_DETECTED_ARMV81M_MAINLINE)

BT_STATIC_ASSERT(FIBER_PORT_DETECTED_COUNT <= 1,
                 "[fiber]: conflicting compiler ARM architecture macros");

#ifndef FIBER_PORT_PROFILE_ALLOW_MISMATCH
# define FIBER_PORT_PROFILE_ALLOW_MISMATCH 0
#endif

BT_STATIC_ASSERT((FIBER_PORT_PROFILE_ALLOW_MISMATCH == 0) || (FIBER_PORT_PROFILE_ALLOW_MISMATCH == 1),
                 "[fiber]: FIBER_PORT_PROFILE_ALLOW_MISMATCH must be 0 or 1");

#define FIBER_PORT_PROFILE_MATCHES_DETECTED \
    ((FIBER_PORT_PROFILE_IS_EXPLICIT == 0) || \
     (FIBER_PORT_DETECTED_COUNT == 0) || \
     ((FIBER_PORT_PROFILE == FIBER_PORT_PROFILE_ARMV6M) && FIBER_PORT_DETECTED_ARMV6M) || \
     ((FIBER_PORT_PROFILE == FIBER_PORT_PROFILE_ARMV7M) && FIBER_PORT_DETECTED_ARMV7M) || \
     ((FIBER_PORT_PROFILE == FIBER_PORT_PROFILE_ARMV7EM) && FIBER_PORT_DETECTED_ARMV7EM) || \
     ((FIBER_PORT_PROFILE == FIBER_PORT_PROFILE_ARMV8M_BASELINE) && FIBER_PORT_DETECTED_ARMV8M_BASELINE) || \
     ((FIBER_PORT_PROFILE == FIBER_PORT_PROFILE_ARMV8M_MAINLINE) && FIBER_PORT_DETECTED_ARMV8M_MAINLINE) || \
     ((FIBER_PORT_PROFILE == FIBER_PORT_PROFILE_ARMV81M_MAINLINE) && FIBER_PORT_DETECTED_ARMV81M_MAINLINE))

BT_STATIC_ASSERT((FIBER_PORT_PROFILE_ALLOW_MISMATCH != 0) || FIBER_PORT_PROFILE_MATCHES_DETECTED,
                 "[fiber]: FIBER_PORT_PROFILE conflicts with compiler __ARM_ARCH_* macros");

/*
 * Legacy explicit override knobs for unusual toolchains. Prefer
 * FIBER_PORT_PROFILE for new projects.
 */
#ifndef FIBER_FORCE_PORT_ARMV6M
# define FIBER_FORCE_PORT_ARMV6M 0
#endif

#ifndef FIBER_FORCE_PORT_ARMV7M
# define FIBER_FORCE_PORT_ARMV7M 0
#endif

#ifndef FIBER_FORCE_PORT_ARMV7EM
# define FIBER_FORCE_PORT_ARMV7EM 0
#endif

#ifndef FIBER_FORCE_PORT_ARMV8M_BASELINE
# define FIBER_FORCE_PORT_ARMV8M_BASELINE 0
#endif

#ifndef FIBER_FORCE_PORT_ARMV8M_MAINLINE
# define FIBER_FORCE_PORT_ARMV8M_MAINLINE 0
#endif

#ifndef FIBER_FORCE_PORT_ARMV81M_MAINLINE
# define FIBER_FORCE_PORT_ARMV81M_MAINLINE 0
#endif

BT_STATIC_ASSERT((FIBER_FORCE_PORT_ARMV6M == 0) || (FIBER_FORCE_PORT_ARMV6M == 1),
                 "[fiber]: FIBER_FORCE_PORT_ARMV6M must be 0 or 1");
BT_STATIC_ASSERT((FIBER_FORCE_PORT_ARMV7M == 0) || (FIBER_FORCE_PORT_ARMV7M == 1),
                 "[fiber]: FIBER_FORCE_PORT_ARMV7M must be 0 or 1");
BT_STATIC_ASSERT((FIBER_FORCE_PORT_ARMV7EM == 0) || (FIBER_FORCE_PORT_ARMV7EM == 1),
                 "[fiber]: FIBER_FORCE_PORT_ARMV7EM must be 0 or 1");
BT_STATIC_ASSERT((FIBER_FORCE_PORT_ARMV8M_BASELINE == 0) || (FIBER_FORCE_PORT_ARMV8M_BASELINE == 1),
                 "[fiber]: FIBER_FORCE_PORT_ARMV8M_BASELINE must be 0 or 1");
BT_STATIC_ASSERT((FIBER_FORCE_PORT_ARMV8M_MAINLINE == 0) || (FIBER_FORCE_PORT_ARMV8M_MAINLINE == 1),
                 "[fiber]: FIBER_FORCE_PORT_ARMV8M_MAINLINE must be 0 or 1");
BT_STATIC_ASSERT((FIBER_FORCE_PORT_ARMV81M_MAINLINE == 0) || (FIBER_FORCE_PORT_ARMV81M_MAINLINE == 1),
                 "[fiber]: FIBER_FORCE_PORT_ARMV81M_MAINLINE must be 0 or 1");

#define FIBER_PORT_FORCE_COUNT \
    (FIBER_FORCE_PORT_ARMV6M + \
     FIBER_FORCE_PORT_ARMV7M + \
     FIBER_FORCE_PORT_ARMV7EM + \
     FIBER_FORCE_PORT_ARMV8M_BASELINE + \
     FIBER_FORCE_PORT_ARMV8M_MAINLINE + \
     FIBER_FORCE_PORT_ARMV81M_MAINLINE)

BT_STATIC_ASSERT(FIBER_PORT_FORCE_COUNT <= 1,
                 "[fiber]: at most one forced Cortex-M port may be selected");

BT_STATIC_ASSERT((FIBER_PORT_PROFILE_IS_EXPLICIT == 0) || (FIBER_PORT_FORCE_COUNT == 0),
                 "[fiber]: use either FIBER_PORT_PROFILE or FIBER_FORCE_PORT_*, not both");

#ifndef FIBER_PORT_ARMV6M
# if FIBER_PORT_PROFILE == FIBER_PORT_PROFILE_ARMV6M
#  define FIBER_PORT_ARMV6M 1
# elif FIBER_PORT_PROFILE_IS_EXPLICIT
#  define FIBER_PORT_ARMV6M 0
# elif FIBER_PORT_FORCE_COUNT
#  define FIBER_PORT_ARMV6M FIBER_FORCE_PORT_ARMV6M
# elif FIBER_PORT_DETECTED_ARMV6M
#  define FIBER_PORT_ARMV6M 1
# else
#  define FIBER_PORT_ARMV6M 0
# endif
#endif

#ifndef FIBER_PORT_ARMV7M
# if FIBER_PORT_PROFILE == FIBER_PORT_PROFILE_ARMV7M
#  define FIBER_PORT_ARMV7M 1
# elif FIBER_PORT_PROFILE_IS_EXPLICIT
#  define FIBER_PORT_ARMV7M 0
# elif FIBER_PORT_FORCE_COUNT
#  define FIBER_PORT_ARMV7M FIBER_FORCE_PORT_ARMV7M
# elif FIBER_PORT_DETECTED_ARMV7M
#  define FIBER_PORT_ARMV7M 1
# else
#  define FIBER_PORT_ARMV7M 0
# endif
#endif

#ifndef FIBER_PORT_ARMV7EM
# if FIBER_PORT_PROFILE == FIBER_PORT_PROFILE_ARMV7EM
#  define FIBER_PORT_ARMV7EM 1
# elif FIBER_PORT_PROFILE_IS_EXPLICIT
#  define FIBER_PORT_ARMV7EM 0
# elif FIBER_PORT_FORCE_COUNT
#  define FIBER_PORT_ARMV7EM FIBER_FORCE_PORT_ARMV7EM
# elif FIBER_PORT_DETECTED_ARMV7EM
#  define FIBER_PORT_ARMV7EM 1
# else
#  define FIBER_PORT_ARMV7EM 0
# endif
#endif

#ifndef FIBER_PORT_ARMV8M_BASELINE
# if FIBER_PORT_PROFILE == FIBER_PORT_PROFILE_ARMV8M_BASELINE
#  define FIBER_PORT_ARMV8M_BASELINE 1
# elif FIBER_PORT_PROFILE_IS_EXPLICIT
#  define FIBER_PORT_ARMV8M_BASELINE 0
# elif FIBER_PORT_FORCE_COUNT
#  define FIBER_PORT_ARMV8M_BASELINE FIBER_FORCE_PORT_ARMV8M_BASELINE
# elif FIBER_PORT_DETECTED_ARMV8M_BASELINE
#  define FIBER_PORT_ARMV8M_BASELINE 1
# else
#  define FIBER_PORT_ARMV8M_BASELINE 0
# endif
#endif

#ifndef FIBER_PORT_ARMV8M_MAINLINE
# if FIBER_PORT_PROFILE == FIBER_PORT_PROFILE_ARMV8M_MAINLINE
#  define FIBER_PORT_ARMV8M_MAINLINE 1
# elif FIBER_PORT_PROFILE_IS_EXPLICIT
#  define FIBER_PORT_ARMV8M_MAINLINE 0
# elif FIBER_PORT_FORCE_COUNT
#  define FIBER_PORT_ARMV8M_MAINLINE FIBER_FORCE_PORT_ARMV8M_MAINLINE
# elif FIBER_PORT_DETECTED_ARMV8M_MAINLINE
#  define FIBER_PORT_ARMV8M_MAINLINE 1
# else
#  define FIBER_PORT_ARMV8M_MAINLINE 0
# endif
#endif

#ifndef FIBER_PORT_ARMV81M_MAINLINE
# if FIBER_PORT_PROFILE == FIBER_PORT_PROFILE_ARMV81M_MAINLINE
#  define FIBER_PORT_ARMV81M_MAINLINE 1
# elif FIBER_PORT_PROFILE_IS_EXPLICIT
#  define FIBER_PORT_ARMV81M_MAINLINE 0
# elif FIBER_PORT_FORCE_COUNT
#  define FIBER_PORT_ARMV81M_MAINLINE FIBER_FORCE_PORT_ARMV81M_MAINLINE
# elif FIBER_PORT_DETECTED_ARMV81M_MAINLINE
#  define FIBER_PORT_ARMV81M_MAINLINE 1
# else
#  define FIBER_PORT_ARMV81M_MAINLINE 0
# endif
#endif

BT_STATIC_ASSERT((FIBER_PORT_ARMV6M == 0) || (FIBER_PORT_ARMV6M == 1),
                 "[fiber]: FIBER_PORT_ARMV6M must be 0 or 1");
BT_STATIC_ASSERT((FIBER_PORT_ARMV7M == 0) || (FIBER_PORT_ARMV7M == 1),
                 "[fiber]: FIBER_PORT_ARMV7M must be 0 or 1");
BT_STATIC_ASSERT((FIBER_PORT_ARMV7EM == 0) || (FIBER_PORT_ARMV7EM == 1),
                 "[fiber]: FIBER_PORT_ARMV7EM must be 0 or 1");
BT_STATIC_ASSERT((FIBER_PORT_ARMV8M_BASELINE == 0) || (FIBER_PORT_ARMV8M_BASELINE == 1),
                 "[fiber]: FIBER_PORT_ARMV8M_BASELINE must be 0 or 1");
BT_STATIC_ASSERT((FIBER_PORT_ARMV8M_MAINLINE == 0) || (FIBER_PORT_ARMV8M_MAINLINE == 1),
                 "[fiber]: FIBER_PORT_ARMV8M_MAINLINE must be 0 or 1");
BT_STATIC_ASSERT((FIBER_PORT_ARMV81M_MAINLINE == 0) || (FIBER_PORT_ARMV81M_MAINLINE == 1),
                 "[fiber]: FIBER_PORT_ARMV81M_MAINLINE must be 0 or 1");

#define FIBER_PORT_COUNT \
    (FIBER_PORT_ARMV6M + \
     FIBER_PORT_ARMV7M + \
     FIBER_PORT_ARMV7EM + \
     FIBER_PORT_ARMV8M_BASELINE + \
     FIBER_PORT_ARMV8M_MAINLINE + \
     FIBER_PORT_ARMV81M_MAINLINE)

BT_STATIC_ASSERT(FIBER_PORT_COUNT == 1,
                 "[fiber]: exactly one Cortex-M port must be selected");

#ifndef FIBER_PORT_IS_BASELINE
# define FIBER_PORT_IS_BASELINE (FIBER_PORT_ARMV6M || FIBER_PORT_ARMV8M_BASELINE)
#endif

#ifndef FIBER_PORT_IS_MAINLINE
# define FIBER_PORT_IS_MAINLINE \
    (FIBER_PORT_ARMV7M || FIBER_PORT_ARMV7EM || FIBER_PORT_ARMV8M_MAINLINE || FIBER_PORT_ARMV81M_MAINLINE)
#endif

#ifndef FIBER_PORT_IS_V8M
# define FIBER_PORT_IS_V8M \
    (FIBER_PORT_ARMV8M_BASELINE || FIBER_PORT_ARMV8M_MAINLINE || FIBER_PORT_ARMV81M_MAINLINE)
#endif

BT_STATIC_ASSERT((FIBER_PORT_IS_BASELINE == 0) || (FIBER_PORT_IS_BASELINE == 1),
                 "[fiber]: FIBER_PORT_IS_BASELINE must be 0 or 1");
BT_STATIC_ASSERT((FIBER_PORT_IS_MAINLINE == 0) || (FIBER_PORT_IS_MAINLINE == 1),
                 "[fiber]: FIBER_PORT_IS_MAINLINE must be 0 or 1");
BT_STATIC_ASSERT((FIBER_PORT_IS_V8M == 0) || (FIBER_PORT_IS_V8M == 1),
                 "[fiber]: FIBER_PORT_IS_V8M must be 0 or 1");
BT_STATIC_ASSERT((FIBER_PORT_IS_BASELINE + FIBER_PORT_IS_MAINLINE) == 1,
                 "[fiber]: selected port must be either baseline or mainline");

#ifndef FIBER_PORT_NAME
# if FIBER_PORT_ARMV6M
#  define FIBER_PORT_NAME "armv6m"
# elif FIBER_PORT_ARMV7M
#  define FIBER_PORT_NAME "armv7m"
# elif FIBER_PORT_ARMV7EM
#  define FIBER_PORT_NAME "armv7em"
# elif FIBER_PORT_ARMV8M_BASELINE
#  define FIBER_PORT_NAME "armv8m_baseline"
# elif FIBER_PORT_ARMV8M_MAINLINE
#  define FIBER_PORT_NAME "armv8m_mainline"
# elif FIBER_PORT_ARMV81M_MAINLINE
#  define FIBER_PORT_NAME "armv81m_mainline"
# endif
#endif

#ifndef FIBER_HAS_BASEPRI
# if FIBER_PORT_IS_MAINLINE
#  define FIBER_HAS_BASEPRI 1
# else
#  define FIBER_HAS_BASEPRI 0
# endif
#endif

#ifndef FIBER_HAS_FAULTMASK
# if FIBER_PORT_IS_MAINLINE
#  define FIBER_HAS_FAULTMASK 1
# else
#  define FIBER_HAS_FAULTMASK 0
# endif
#endif

#ifndef FIBER_HAS_PSPLIM
# if FIBER_PORT_ARMV8M_MAINLINE || FIBER_PORT_ARMV81M_MAINLINE
#  define FIBER_HAS_PSPLIM 1
# else
#  define FIBER_HAS_PSPLIM 0
# endif
#endif

#ifndef FIBER_HAS_MVE
# if defined(__ARM_FEATURE_MVE) && (__ARM_FEATURE_MVE > 0)
#  define FIBER_HAS_MVE 1
# else
#  define FIBER_HAS_MVE 0
# endif
#endif

BT_STATIC_ASSERT((FIBER_HAS_BASEPRI == 0) || (FIBER_HAS_BASEPRI == 1),
                 "[fiber]: FIBER_HAS_BASEPRI must be 0 or 1");
BT_STATIC_ASSERT((FIBER_HAS_FAULTMASK == 0) || (FIBER_HAS_FAULTMASK == 1),
                 "[fiber]: FIBER_HAS_FAULTMASK must be 0 or 1");
BT_STATIC_ASSERT((FIBER_HAS_PSPLIM == 0) || (FIBER_HAS_PSPLIM == 1),
                 "[fiber]: FIBER_HAS_PSPLIM must be 0 or 1");
BT_STATIC_ASSERT((FIBER_HAS_MVE == 0) || (FIBER_HAS_MVE == 1),
                 "[fiber]: FIBER_HAS_MVE must be 0 or 1");

#endif /* FIBER_PORT_FIBER_PORT_SELECT_H_ */
