/*
 * fiber_port_transitional_v8m.h
 *
 * Transitional selected-port interface for v8-M profiles that do not yet have
 * concrete FreeRTOS-style port sources.
 */

#ifndef FIBER_PORT_TRANSITIONAL_V8M_FIBER_PORT_TRANSITIONAL_V8M_H_
#define FIBER_PORT_TRANSITIONAL_V8M_FIBER_PORT_TRANSITIONAL_V8M_H_

#include "../../target/fiber_target.h"
#include "../fiber_port_types.h"

#ifndef FIBER_PORT_NAME
# define FIBER_PORT_NAME "transitional_v8m"
#endif

#ifndef FIBER_PORT_TRAITS_LEGACY_BRIDGE
# define FIBER_PORT_TRAITS_LEGACY_BRIDGE 1
#endif

#define FIBER_PORT_HAS_BASEPRI FIBER_HAS_BASEPRI
#define FIBER_PORT_HAS_FAULTMASK FIBER_HAS_FAULTMASK

#ifndef FIBER_PORT_HAS_VTOR
# if FIBER_PORT_IS_MAINLINE
#  define FIBER_PORT_HAS_VTOR 1
# elif defined(SCB_VTOR_TBLOFF_Msk) || \
		(defined(__VTOR_PRESENT) && ((__VTOR_PRESENT + 0) != 0))
#  define FIBER_PORT_HAS_VTOR 1
# else
#  define FIBER_PORT_HAS_VTOR 0
# endif
#endif

#define FIBER_PORT_HAS_PSPLIM FIBER_HAS_PSPLIM
#define FIBER_PORT_HAS_FPU FIBER_HAS_FPU
#define FIBER_PORT_HAS_EXTENDED_FP_CONTEXT FIBER_HAS_EXTENDED_FP_CONTEXT
#define FIBER_PORT_BOOT_CLEARS_FPCA (FIBER_HAS_FPU && FIBER_BOOT_CLEAR_FPCA)
#define FIBER_PORT_HAS_MVE FIBER_HAS_MVE
#define FIBER_PORT_HAS_PAC FIBER_HAS_PAC
#define FIBER_PORT_HAS_BTI FIBER_HAS_BTI
#define FIBER_PORT_USES_PSPLIM_REGISTER FIBER_USE_PSPLIM_REGISTER
#define FIBER_PORT_INITIAL_EXC_RETURN FIBER_INITIAL_EXC_RETURN
#define FIBER_PORT_SCHEDULER_MASK_KIND \
	(FIBER_PORT_IS_BASELINE ? FIBER_PORT_MASK_PRIMASK : FIBER_PORT_MASK_BASEPRI)

#if FIBER_PORT_SCHEDULER_MASK_KIND == FIBER_PORT_MASK_BASEPRI
# define FIBER_PORT_SCHEDULER_BASEPRI FIBER_SCHEDULER_BASEPRI
#endif

#define FIBER_PORT_SUPPORTS_M7_R0P1_ERRATA_WORKAROUND 0
#define FIBER_PORT_ENABLE_M7_R0P1_ERRATA_WORKAROUND 0
#ifndef FIBER_PORT_IS_V8M
# define FIBER_PORT_IS_V8M 1
#endif

#ifndef FIBER_PORT_HAS_SECURITY_EXT
# if defined(__ARM_FEATURE_CMSE) && ((__ARM_FEATURE_CMSE + 0) >= 3)
#  define FIBER_PORT_HAS_SECURITY_EXT 1
# else
#  define FIBER_PORT_HAS_SECURITY_EXT 0
# endif
#endif

#define FIBER_PORT_RUNS_NONSECURE FIBER_RUN_NONSECURE

#ifndef FIBER_PORT_TARGETS_NS_BANK
# if defined(FIBER_TZ_NS) && (FIBER_TZ_NS + 0)
#  define FIBER_PORT_TARGETS_NS_BANK 1
# else
#  define FIBER_PORT_TARGETS_NS_BANK 0
# endif
#endif

#define FIBER_PORT_HAS_CONTROL_SLOT 0
#define FIBER_PORT_HAS_PSPLIM_SLOT 0
#define FIBER_PORT_HAS_SECURE_CONTEXT_SLOT 0
#define FIBER_PORT_HAS_PAC_KEY_SLOT 0

#define FIBER_PORT_SOFTWARE_FRAME_WORDS 9u
#define FIBER_PORT_SOFTWARE_FRAME_BYTES (FIBER_PORT_SOFTWARE_FRAME_WORDS * 4u)
#define FIBER_PORT_EXC_RETURN_WORD_INDEX (FIBER_PORT_IS_BASELINE ? 0u : 8u)

#ifdef __cplusplus
extern "C" {
#endif

void fiber_port_init_context_frame(FiberContext *ctx);

FIBER_NORETURN
void fiber_port_start_first_context(uintptr_t msp_top);

FIBER_ATTR_NAKED_ASM
void fiber_svc(void);

FIBER_ATTR_NAKED_ASM
void fiber_pendsv(void);

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif /* FIBER_PORT_TRANSITIONAL_V8M_FIBER_PORT_TRANSITIONAL_V8M_H_ */
